/* eslint-disable import/no-anonymous-default-export */
export default [
  { letter: "A", key: 1 },
  { letter: "B", key: 2 },
  { letter: "C", key: 3 },
  { letter: "D", key: 4 },
  { letter: "E", key: 5 },
  { letter: "F", key: 6 },
  { letter: "G", key: 7 },
  { letter: "H", key: 8 },
  { letter: "I", key: 9 },
  { letter: "J", key: 10 },
  { letter: "K", key: 11 },
  { letter: "L", key: 12 },
  { letter: "M", key: 13 },
  { letter: "N", key: 14 },
  { letter: "O", key: 15 },
  { letter: "P", key: 16 },
  { letter: "Q", key: 17 },
  { letter: "R", key: 18 },
  { letter: "S", key: 19 },
  { letter: "T", key: 20 },
  { letter: "U", key: 21 },
  { letter: "V", key: 22 },
  { letter: "W", key: 23 },
  { letter: "X", key: 24 },
  { letter: "Y", key: 25 },
  { letter: "Z", key: 26 },
];
